### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by muffinbarde** [Lucid-Lucie/Alchemist#4]
[https://ufile.io/8s3kzbj8](https://ufile.io/8s3kzbj8)

**Comment by Lucid-Lucie** [comment]
Hello! Thank you so much for your translation! A lot of school work for me has made the project stale but I will have a free weekend next week and will try to implement the translation and credits as soon as possible!

Dankeschön!

**Comment by muffinbarde** [comment]
You're welcome!

**Comment by Lucid-Lucie** [comment]
Translation is now added! Your credited in the credits, language file, and on the mod page in the update when it is released. Thank you for your help!
